### ISSUE TITLE
/opt/set-gpu-fans/nvscmd: 84: /opt/set-gpu-fans/nvscmd: Syntax error: "(" unexpected (expecting "fi")

### ISSUE THREAD

**Issue by paulcx** [boris-dimitrov/set_gpu_fans_public#3]
[1] 20166
Persistence mode is already Enabled for GPU 0000:02:00.0.
Persistence mode is already Enabled for GPU 0000:81:00.0.
All done.

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic x86_64 Ubuntu
Current Operating System: Linux WAIR-P8000 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-83-generic root=UUID=512494ce-8ef7-4b2f-8996-d81639985410 ro text
Build Date: 17 July 2017  05:05:12PM
xorg-server 2:1.18.4-0ubuntu0.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Wed Jul 26 17:16:09 2017
(++) Using config file: "/tmp/xorg-aryyQphn.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/opt/set-gpu-fans/nvscmd: 84: /opt/set-gpu-fans/nvscmd: Syntax error: "(" unexpected (expecting "fi")
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

I'm wondering if there is a fix for this error?

**Comment by boris-dimitrov** [comment]
It appears that in this case the "nvscmd" script was executed by the bash shell instead of the tcsh shell.   The '#!/bin/tcsh -f" line at the top of the script should have ensured its execution under tcsh.   Is it possible that somehow on this system /bin/tcsh is a link to bash?   Installing tcsh should help in that case.

**Comment by paulcx** [comment]
@boris-dimitrov Installing tcsh does help! However, it seems to be stoped before running? I'm wondering if this is related to the setting of Xmanager?

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic x86_64 Ubuntu
Current Operating System: Linux WAIR-P8000 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-87-generic root=UUID=512494ce-8ef7-4b2f-8996-d81639985410 ro text
Build Date: 17 July 2017  05:05:12PM
xorg-server 2:1.18.4-0ubuntu0.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Thu Jul 27 09:29:38 2017
(++) Using config file: "/tmp/xorg-UabLuiFS.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
foo: Subscript out of range.
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.
