### ISSUE TITLE
watt cannot increase

### ISSUE THREAD

**Issue by wiryonolau** [boris-dimitrov/set_gpu_fans_public#4]
Hi I'm using both Alex and your version. I have GTX1070, the fan is increase to what I want. But during calculation the power (Watt) cannot go beyond 25W, does it happen in your server ?

**Comment by burnzzz** [comment]
I´m having the same issue. it really limits the GPU in spending more than 28W in my case. This cuts performance of GPU tasks to 10% of possible 100% in my case (1080 GTX). Any idea what´s the cause?

**Comment by wiryonolau** [comment]
Hi, I just resolve it yesterday, thanks for the code. Not just the fan even
the oc is working.

I use Ubuntu 16.04 with driver 384 for my GTX1070. You can put it in
systemd to run at boot but it has to be the last service running.

**Comment by boris-dimitrov** [comment]
Thanks for reporting the issue.   I am glad you were able to resolve it.
